import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "remixicon/fonts/remixicon.css";
import ScrollTop from "@/components/ScrollTop";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Company Profile",
  description: "Generated by JyCodee",
  icons: {
    icon: "/company-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body className={`${fontPoppins.className} antialiased`}>
        <ScrollTop />
        <Navbar />
        <div className="container mx-auto px-20">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
